apiVersion: apps/v1
kind: Deployment
metadata:
  name: fliteconsulting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fliteconsulting
  template:
    metadata:
      labels:
        app: fliteconsulting
    spec:
      containers:
      - name: fliteconsulting
        image: registry.digitalocean.com/flite-registry/fliteconsulting:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: flite-registry