apiVersion: apps/v1
kind: Deployment
metadata:
  name: fliteconsulting-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fliteconsulting
  template:
    metadata:
      labels:
        app: fliteconsulting
    spec:
      containers:
      - name: fliteconsulting
        image: flite/fliteconsulting:latest
        ports:
        - containerPort: 80